import {
  MdArrowDownward,
  MdArrowRight,
  MdCancel,
  MdChevronLeft,
  MdChevronRight,
  MdClearAll,
  MdClose,
  MdContentCopy,
  MdDensityLarge,
  MdDensityMedium,
  MdDensitySmall,
  MdDragHandle,
  MdDynamicFeed,
  MdEdit,
  MdExpandMore,
  MdFilterAlt,
  MdFilterList,
  MdFilterListOff,
  MdFirstPage,
  MdFullscreen,
  MdFullscreenExit,
  MdKeyboardDoubleArrowDown,
  MdLastPage,
  MdMoreHoriz,
  MdMoreVert,
  MdPushPin,
  MdRestartAlt,
  MdSave,
  MdSearch,
  MdSearchOff,
  MdSort,
  MdSyncAlt,
  MdViewColumn,
  MdVisibilityOff
} from 'react-icons/md';

export const MRT_Default_Icons = {
  ArrowDownwardIcon: MdArrowDownward,
  ArrowRightIcon: MdArrowRight,
  CancelIcon: MdCancel,
  ChevronLeftIcon: MdChevronLeft,
  ChevronRightIcon: MdChevronRight,
  ClearAllIcon: MdClearAll,
  CloseIcon: MdClose,
  ContentCopy: MdContentCopy,
  DensityLargeIcon: MdDensityLarge,
  DensityMediumIcon: MdDensityMedium,
  DensitySmallIcon: MdDensitySmall,
  DragHandleIcon: MdDragHandle,
  DynamicFeedIcon: MdDynamicFeed,
  EditIcon: MdEdit,
  ExpandMoreIcon: MdExpandMore,
  FilterAltIcon: MdFilterAlt,
  FilterListIcon: MdFilterList,
  FilterListOffIcon: MdFilterListOff,
  FirstPageIcon: MdFirstPage,
  FullscreenExitIcon: MdFullscreenExit,
  FullscreenIcon: MdFullscreen,
  KeyboardDoubleArrowDownIcon: MdKeyboardDoubleArrowDown,
  LastPageIcon: MdLastPage,
  MoreHorizIcon: MdMoreHoriz,
  MoreVertIcon: MdMoreVert,
  PushPinIcon: MdPushPin,
  RestartAltIcon: MdRestartAlt,
  SaveIcon: MdSave,
  SearchIcon: MdSearch,
  SearchOffIcon: MdSearchOff,
  SortIcon: MdSort,
  SyncAltIcon: MdSyncAlt,
  ViewColumnIcon: MdViewColumn,
  VisibilityOffIcon: MdVisibilityOff,
} as const;

export type MRT_Icons = Record<keyof typeof MRT_Default_Icons, any>;
